h1: Develop and Run Web & Mobile Apps

h2:
  prefix: Full-Stack JavaScript Platform
  typing:
    - <strong>for Web<span class="highlighted"> &plus; </span>Hybrid<span class="highlighted"> &plus; </span>Native</strong>
    - <strong>from code<span class="highlighted"> to </span> go live!</strong>

feature_highlights:
  - p: Open Source Platform
    img:
      url: img/open-source.png
      alt: Open Source
    class: offset-lg-1 offset-md-2 col-lg-2 col-md-4

  - p: Connect to external DB or Web Service
    img:
      url: img/data-source.png
      alt: Data Source
    class: col-lg-2 col-md-4

  - p: IDE Mac & Windows
    img:
      url: img/mac-win.png
      alt: macOS and Windows
    class: col-lg-2 col-md-4

  - p: Server On-Prem In the Cloud
    img:
      url: img/premise-cloud.png
      alt: On Premise and in the Cloud
    class: col-lg-2 col-md-4

  - p: Mobile Web Apps AngularJS & Ionic
    img:
      url: img/mobile-apps.png
      alt: Mobile Apps
    class: col-lg-2 col-md-4

feature_details:


  column_right:
    h3: Wakanda 2.0 is coming soon!
    items:
      - h4: NodeJS Support
        p: Develop Server Side JS in Single Threaded Event Loop architecture. Get access to more than 230,000 modules!

        img:
          url: img/icons/node.png
          alt: Integrate

      - h4: JavaScript Abstract Layer
        p: Whatever the datasource (Relational DB, Web Services, …), integrate your business entities directly, add security layer or events.

        img:
          url: img/icons/abstractJS.png
          alt: Integrate

      - h4: New DataBases are supported
        p: Wakanda DB like! Thanks to the new ODBC Connector, integrate to Wakanda MSSQL DB and manipulate directly business entities.
        img:
          url: img/icons/mssql.png
          alt: Integrate

slideshow:
  - video:
      id: 196703573
      alt: Templates
    # If have more than one video, you can define navigation buttons like this:
    # btn: <i class="fa fa-magic" aria-hidden="true"></i> Templates
    title: Full Platform to develop, build, deploy and run your Apps
    url: /get-started

quotes:
  - p: Incredible work guys, wakanda looks stunning!!!!
    author:
      name: João
      username: "@Djayci"
      url: https://twitter.com/DjayCi/status/791280762918232064
      img: https://pbs.twimg.com/profile_images/3440695201/10bb1785880137833ab77639791c15b2.png

  - p: To all @angularjs & @Ionicframework developers, I would highly recommend checking out the @wakandasoft platform!
    author:
      name: Corey
      username: "@thecoreyshelton"
      url: https://twitter.com/thecoreyshelton/status/809485633316130816
      img: https://pbs.twimg.com/profile_images/549945253977804800/JOx5qkcX.jpeg
  # You can set more than 2 quotes, a carousel will automatically be used.

mail_form:
  title: Wakanda 2.0 is coming soon!
  p: "Enter your email to be added to the invite list:"

community:
  - title: Ask questions on Stackoverflow
    icon: fa fa-stack-overflow
    url: http://stackoverflow.com/questions/tagged/wakanda
  - title: Report issues, request new features
    icon: fa fa-github
    url: https://github.com/Wakanda/wakanda-issues/issues
  - title: Read our engineering blog
    icon: fa fa-rss
    url: https://blog.wakanda.io/category/developers

event:
  title: Next Wakanda & JavaScript events
  paragraphs:
    - We can help you start a new JavaScript Meetup. <a href="javascript:void(0);" onclick="olark('api.box.expand')">Contact us!</a>
  calendar:
  - month: April
    day: 19
    title: User testing session
    p: Test the next version. Get a $50 Amazon gift card
    url: http://try.wakanda.io/user-test/
  - month: April
    day: 26
    title: User testing session
    p: Test our next version. Get a $50 Amazon gift card
    url: http://try.wakanda.io/user-test/

services:
  - title: Server
    image: img/serverLogo@2x.png
    id: server
    items:
      - orientation: right
        title: Use Wakanda DB or any 3rd-party DB
        id: db-3rd-party
        description: "Manipulate your data with an elegant Javascript syntax (newSQL).<br/>An Object Relational Mapping framework (ORM) in Javascript for any data sources."
        link: "#"
        image: "/img/illu_database.svg"
      - orientation: left
        title: Code in Javascript from A to Z
        id: js-a-z
        description: "No lock-in: totally open source SSJS Application server. <br/>Designed for productivity: reuse your business code with module management.<br/>One-click deployment."
        link: "#"
        image: "/img/illu_server-side.svg"
      - orientation: right
        title: "RESTful API"
        id: rest-api
        description: "Data models accessible through autogenerated REST API. <br/>Fine-tuned permission management."
        link: "#"
        image: "/img/illu_api.svg"
      - orientation: left
        title: "Popular front-end frameworks integration"
        id: front-end
        description: "Use the strength of Angular with or connector: bind your data to your front-end easily. <br/>And soon, many other integrations : React, Aurelia..."
        link: "#"
        image: "/img/illu_angularionic.svg"
  - title: Studio
    image: img/studioLogo@2x.png
    id: studio
    items:
      - orientation: right
        title: All-in-one IDE for Mac or Windows
        id: all-ide
        description: "Develop your Front-End, Back-End and integrate your data in the same IDE. <br/>Full workflow covered from dev to deployment. <br/>Start coding in a minute: guided setup, preconfigured projects,all libraries you need already integrated. <br/>IDE customizable with extensions."
        link: "#"
        image: "/img/illu_allinone.svg"
      - orientation: left
        title: Visual Data Modelling
        id: visual-data
        description: "Design visually local or remote data models (MySQL, Oracle...).<br/> Manage its methods and permissions. <br/>Autogenerate your data model's JSON."
        link: "#"
        image: "/img/illu_visualdata.svg"
      - orientation: right
        title: "Shaped for Mobile and Web Apps"
        id: mobile-web
        description: "Build omnichannel apps with a single Back-End for multiple mobile and web Front-End.<br/>Specific project templates and previsualisation tools for web and mobile apps.<br/>All platforms are supported."
        link: "#"
        image: "/img/illu_webmobileapps.svg"